// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hypjyzlbbfqoabwvcdfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cGp5emxiYmZxb2Fid3ZjZGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTAwMzYsImV4cCI6MjA2Mjg4NjAzNn0.Or1srzHAiAga5m0vSa9zRyAcgNp4xDjCukWzn8PAE94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);